# -*- coding: utf-8 -*-
"""goodcrawl.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zpm7iMWwXMlYWFEsA6eUgIsMbZRGozYS
"""

import tweepy
import re
import pandas as pd
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
factory = StemmerFactory()
stemmer = factory.create_stemmer()
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
factory = StopWordRemoverFactory()
stopword = factory.create_stop_word_remover()
access_token="1375292174279962625-SWmfVFnq8yRNoOqZcW6hsYlqa7UR6N"
access_token_secret="qanrWREjs7MxRE84i6YzhqLqjex7spaNlX7TsAQjFfgyO"
consumer_key="MQX4CafGNJIYnPC0ekE6xCEux"
consumer_secret="zqLqMPmqVPw8Lxqgj3oRchEKk3yU9qC9Hk9h1YkjbG0gmP6HP8"
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth,wait_on_rate_limit=True, wait_on_rate_limit_notify=True)
# searchQuery = '#COVID'
# retweet_filter='-filter:retweets'


#script goes here
data=[]
n = 0
for tweet in tweepy.Cursor(api.search, q='#COVID -filter:retweets',lang="id", since='2020-10-01', until='2021-04-06').items(400):
    name = tweet.user.name
    user = tweet.user.screen_name
    lokasi = tweet.user.location
    desc = tweet.user.description
    n = n + 1
    # print(tweet)
    # print(username)
#     hasil1=re.sub(r'\w+:\/{2}[\d\w-]+(\.[\d\w-]+)*(?:(?:\/[^\s/]*))*', '', tweet)
#     hasil2= hasil1.encode('ascii', 'ignore').decode('ascii')
#     hasil3=' '.join(word for word in hasil2.split(' ') if not word.startswith('#'))
#     hasil4=' '.join(word for word in hasil3.split(' ') if not word.startswith('@'))
#     katadasar = stemmer.stem(str(hasil4))
#     stop = stopword.remove(katadasar)
#     hasil5=(" ".join(stop.split()))
    data.append([name,user,lokasi,desc])
datatw = pd.DataFrame(data)
datatw.index.name = 'Index'
print(n)
datatw.to_csv("tweetkemenkes.csv",header=["Nama", "Username", "Lokasi","Description"])

# untuk dedupe dilakukan dengan parameter Tweet, Name, Location, User Desc

pip install tweepy

pip install Sastrawi